---
# Install conver2rhel packages

- name: unwanted packages are removed
  package:
    name: "{{ conver2rhel_packages_remove }}"
    state: absent
  become: true
  when: conver2rhel_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ conver2rhel_packages_repos }}"
    state: "{{ conver2rhel_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ conver2rhel_packages_prereq }}"
    state: "{{ conver2rhel_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ conver2rhel_packages_install }}"
    state: "{{ conver2rhel_packages_state }}"
  become: true
